services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - qdrantdb
    environment:
      - QDRANT_URL=http://qdrantdb:6333
    volumes:
      - .:/app

  qdrantdb:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z

volumes:
  qdrant_storage:
